# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: generic

sudo: false

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-5
      - binutils
      - build-essential
      - libopenmpi-dev
      - python-pip
      - liblapack-dev

before_install:
    - git submodule update --init --recursive

# trick mpi into using our custom gfortran install
before_script:
    - mkdir -p $HOME/.local/bin
    - export PATH="$HOME/.local/bin:${PATH}"
    - |
      if [[ ! -L "$HOME/.local/bin/gfortran" ]]; then
         ln -s `which gfortran-5` $HOME/.local/bin/gfortran
      fi

script:
    - make clean && make FC='mpif90'
    - make clean && make FC='gfortran-5'
    - make clean && cp input/example_defines/LAM_attraction_base.inc src/defines && make FC='mpif90'
    - make clean && cp input/example_defines/MBS_PNAS_2018_baseCase.inc src/defines && make FC='mpif90'
    - make clean && cp input/example_defines/sedona_base.inc src/defines && make FC='mpif90'
    - make clean && cp input/example_defines/simple_DNA.inc src/defines && make FC='gfortran-5'
